name: Deploy ghPage PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    paths:
      - 'docs/**'
      - '**.md'
      - '**.html'

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1.1.1
        if: contains(['opened', 'reopened', 'synchronize'], github.event.action)
        with:
          preview-branch: gh-pages
          action: deploy
      - name: Delete PR Preview
        uses: rossjrw/pr-preview-action@v1.1.1
        if: github.event.action == "closed"
        with:
          preview-branch: gh-pages
          action: remove

