name: Deploy PR previews
concurrency: preview-${{ github.ref }}
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
#       - name: Install and Build
#         run: |
#           npm install
#           npm run build
      - name: Deploy/Remove PR Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: .
          preview-branch: master
          umbrella-dir: pr-preview
          action: auto
          
